<?php
require_once __DIR__ . '/../rdb/RDB.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-14 at 18:31:49.
 */
class RDBTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var \RDB\RDB
     */
    protected $rdb;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->rdb = new \RDB\RDB;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testEmptyDatabase()
    {
        $file = __DIR__ . '/dumps/empty_database.rdb';

        $this->rdb->setFile( $file );

//        $this->assertGreaterThanOrEqual( 3, $this->rdb->getVersion(), 'Expected redis file format >= 3' );

        $this->rdb->read();
    }


    public function testIntSet16()
    {
        $file = __DIR__ . '/dumps/intset_16.rdb';

        $this->rdb->setFile( $file );

//        $this->assertGreaterThanOrEqual( 3, $this->rdb->getVersion(), 'Expected redis file format >= 3' );

        $this->rdb->read();
    }
}
