<?php
require_once __DIR__ . '/../rdb/RDB.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-14 at 18:31:49.
 */
class RDBTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var \RDB\RDB
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RDB\RDB;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testEmptyDatabase()
    {
        $file = __DIR__ . '/dumps/empty_database.rdb';

        $this->object->setFile( $file );
        $this->object->read();
    }
}
